package probe

import (
	"fmt"
	"sort"
	"strings"
)

// RenderCLISurfaceMarkdown renders the dedicated Atlas CLI help/flag surface
// report. It is separate from gaps.md because it measures the pinned Atlas CE
// binary's command tree, not the vendored fixture corpus.
func RenderCLISurfaceMarkdown(results []Result, w *Waivers, inventory CLISurfaceInventory, ptahVersion, command string) string {
	s := summarize(results)
	nonOK := NonOK(results)
	unwaived := Unwaived(results, w)

	var b strings.Builder
	b.WriteString("# Ptah vs Atlas — CLI surface report\n\n")
	fmt.Fprintf(&b, "This file is generated by `%s`. Do not edit by hand.\n\n", command)
	b.WriteString("It records the command paths, help usage, and long flags exposed by the pinned\n")
	b.WriteString("Atlas CE binary, then compares them with both Ptah compatibility surfaces:\n")
	b.WriteString("`ptah atlas <command>` and a `ptah-compat` binary named `atlas`.\n\n")

	if len(nonOK) == 0 {
		b.WriteString("## Status: CLI SURFACE PARITY\n\n")
		b.WriteString("Every discovered OSS Atlas CE command has matching Ptah help usage and flags.\n\n")
	} else {
		fmt.Fprintf(&b, "## Status: NOT DONE — %d non-OK observation(s)\n\n", len(nonOK))
		b.WriteString("The full CLI-surface gate is red until Ptah's Atlas namespace and drop-in\n")
		b.WriteString("compatibility binary match the pinned Atlas CE help surface.\n\n")
	}

	fmt.Fprintf(&b, "- Atlas CE binary: `%s`\n", inventory.AtlasVersion)
	fmt.Fprintf(&b, "- Ptah at `%s`\n", ptahVersion)
	fmt.Fprintf(&b, "- Outcomes: **%d ok**, **%d gap**, **%d fail**, **%d panic**\n", s.OK, s.Gap, s.Fail, s.Panic)
	fmt.Fprintf(&b, "- Full gate: **%d non-OK** (%s)\n", len(nonOK), conformanceGateStatus(len(nonOK)))
	fmt.Fprintf(&b, "- Regression budget input: **%d unwaived non-OK**, %d waived\n",
		len(unwaived),
		s.Gap+s.Fail+s.Panic-len(unwaived),
	)

	writeCLISurfaceInventory(&b, inventory)
	writeCLISurfaceFindings(&b, results, w)
	writeCLISurfaceIssues(&b, results)
	return b.String()
}

func writeCLISurfaceInventory(b *strings.Builder, inventory CLISurfaceInventory) {
	b.WriteString("\n## Atlas CE Inventory\n\n")
	b.WriteString("| Command | Class | Usage | Flags | Reason |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, cmd := range inventory.Commands {
		flags := strings.Join(cmd.Flags, " ")
		if flags == "" {
			flags = "—"
		}
		usage := cmd.Usage
		if usage == "" {
			usage = "—"
		}
		fmt.Fprintf(b, "| `%s` | %s | `%s` | `%s` | %s |\n",
			displayCommand("atlas", cmd.Path),
			cmd.Classification,
			escapePipe(usage),
			escapePipe(flags),
			escapePipe(cmd.ClassificationReason),
		)
	}
}

func writeCLISurfaceFindings(b *strings.Builder, results []Result, w *Waivers) {
	order := map[Outcome]int{Panic: 0, Fail: 1, Gap: 2, OK: 3}
	sorted := append([]Result(nil), results...)
	sort.SliceStable(sorted, func(i, j int) bool {
		if order[sorted[i].Outcome] != order[sorted[j].Outcome] {
			return order[sorted[i].Outcome] < order[sorted[j].Outcome]
		}
		if sorted[i].Probe != sorted[j].Probe {
			return sorted[i].Probe < sorted[j].Probe
		}
		if sorted[i].Fixture != sorted[j].Fixture {
			return sorted[i].Fixture < sorted[j].Fixture
		}
		return sorted[i].Stage < sorted[j].Stage
	})

	b.WriteString("\n## Findings\n\n")
	b.WriteString("| Gate | Outcome | Probe | Command | Stage | Detail | Related |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
	for _, r := range sorted {
		issue := ""
		if r.Issue != "" {
			issue = "#" + strings.TrimPrefix(r.Issue, "stokaro/ptah#")
		}
		gate := "—"
		if r.Outcome != OK {
			gate = "**RED**"
			if _, ok := w.Reason(r); ok {
				gate = "waived"
			}
		}
		fmt.Fprintf(b, "| %s | %s | %s | `%s` | %s | %s | %s |\n",
			gate, badge(r.Outcome), r.Probe, r.Fixture, r.Stage, escapePipe(r.Detail), issue)
	}
}

func writeCLISurfaceIssues(b *strings.Builder, results []Result) {
	byIssue := map[string]int{}
	for _, r := range results {
		if r.Outcome != OK && r.Issue != "" {
			byIssue[r.Issue]++
		}
	}
	if len(byIssue) == 0 {
		return
	}
	b.WriteString("\n## Gaps by related issue\n\n")
	keys := make([]string, 0, len(byIssue))
	for issue := range byIssue {
		keys = append(keys, issue)
	}
	sort.Strings(keys)
	for _, issue := range keys {
		fmt.Fprintf(b, "- **%s** — %d finding(s)\n", issue, byIssue[issue])
	}
}
