package probe

import (
	"fmt"
	"sort"
	"strings"
)

// Summary counts outcomes across a run.
type Summary struct {
	OK, Gap, Fail, Panic int
}

func summarize(results []Result) Summary {
	var s Summary
	for _, r := range results {
		switch r.Outcome {
		case OK:
			s.OK++
		case Gap:
			s.Gap++
		case Fail:
			s.Fail++
		case Panic:
			s.Panic++
		}
	}
	return s
}

// Unwaived returns the gaps/fails/panics not covered by waivers. This is the
// regression budget input; full conformance uses NonOK.
func Unwaived(results []Result, w *Waivers) []Result {
	var out []Result
	for _, r := range results {
		if r.Outcome == OK {
			continue
		}
		if _, ok := w.Reason(r); ok {
			continue
		}
		out = append(out, r)
	}
	return out
}

// RenderMarkdown produces gaps.md: a ranked, grouped report. atlasSHA and
// ptahVersion are recorded so the report is reproducible.
func RenderMarkdown(results []Result, w *Waivers, atlasSHA, ptahVersion string) string {
	s := summarize(results)
	nonOK := NonOK(results)
	unwaived := Unwaived(results, w)
	var b strings.Builder

	b.WriteString("# Ptah vs Atlas — coverage gap report\n\n")
	b.WriteString("This file is generated by `make probe`. Do not edit by hand.\n\n")
	b.WriteString("It records where Ptah, driven through its public API, cannot ingest what Atlas\n")
	b.WriteString("authored. It is a coverage probe over Atlas's own fixtures, not a quality score:\n")
	b.WriteString("a `gap` here is a thing Atlas expresses that Ptah does not yet.\n\n")

	if len(nonOK) == 0 {
		b.WriteString("## Status: PARITY on the current corpus\n\n")
		b.WriteString("Every fixture is covered. The conformance gate is green.\n\n")
	} else {
		fmt.Fprintf(&b, "## Status: NOT DONE — %d non-OK observation(s)\n\n", len(nonOK))
		b.WriteString("The conformance gate is **red** and stays red until these close. This is by\n")
		b.WriteString("design: the report is a spec Ptah has not met yet, not a passing test log.\n\n")
	}

	fmt.Fprintf(&b, "- Atlas fixtures pinned at `ariga/atlas@%s`\n", atlasSHA)
	fmt.Fprintf(&b, "- Ptah at `%s`\n", ptahVersion)
	fmt.Fprintf(&b, "- Outcomes: **%d ok**, **%d gap**, **%d fail**, **%d panic**\n", s.OK, s.Gap, s.Fail, s.Panic)
	fmt.Fprintf(&b, "- Full gate: **%d non-OK** (%s)\n",
		len(nonOK),
		conformanceGateStatus(len(nonOK)),
	)
	fmt.Fprintf(&b, "- Regression budget input: **%d unwaived non-OK**, %d waived\n",
		len(unwaived),
		s.Gap+s.Fail+s.Panic-len(unwaived),
	)
	writeCorpusSummary(&b, results)
	b.WriteString("\n")

	// Gaps/fails/panics first — the actionable part — most severe first.
	order := map[Outcome]int{Panic: 0, Fail: 1, Gap: 2, OK: 3}
	sorted := append([]Result(nil), results...)
	sort.SliceStable(sorted, func(i, j int) bool {
		if order[sorted[i].Outcome] != order[sorted[j].Outcome] {
			return order[sorted[i].Outcome] < order[sorted[j].Outcome]
		}
		if sorted[i].Probe != sorted[j].Probe {
			return sorted[i].Probe < sorted[j].Probe
		}
		return sorted[i].Fixture < sorted[j].Fixture
	})

	b.WriteString("## Findings\n\n")
	b.WriteString("| Gate | Outcome | Probe | Fixture | Stage | Detail | Related |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
	for _, r := range sorted {
		issue := ""
		if r.Issue != "" {
			issue = "#" + strings.TrimPrefix(r.Issue, "stokaro/ptah#")
		}
		gate := ""
		switch {
		case r.Outcome == OK:
			gate = "—"
		default:
			if _, ok := w.Reason(r); ok {
				gate = "waived"
			} else {
				gate = "**RED**"
			}
		}
		fmt.Fprintf(&b, "| %s | %s | %s | `%s` | %s | %s | %s |\n",
			gate, badge(r.Outcome), r.Probe, r.Fixture, r.Stage, escapePipe(r.Detail), issue)
	}

	// Per-issue rollup so the report doubles as a backlog for ptah.
	byIssue := map[string]int{}
	for _, r := range results {
		if r.Outcome != OK && r.Issue != "" {
			byIssue[r.Issue]++
		}
	}
	if len(byIssue) > 0 {
		b.WriteString("\n## Gaps by related issue\n\n")
		keys := make([]string, 0, len(byIssue))
		for k := range byIssue {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "- **%s** — %d finding(s)\n", k, byIssue[k])
		}
	}

	return b.String()
}

func conformanceGateStatus(nonOK int) string {
	if nonOK == 0 {
		return "passes CI"
	}
	return "fails CI"
}

func writeCorpusSummary(b *strings.Builder, results []Result) {
	var imported, measured, unmeasured int
	for _, r := range results {
		if r.Probe != "corpus-inventory" {
			continue
		}
		imported++
		if r.Outcome == OK {
			measured++
		} else {
			unmeasured++
		}
	}
	if imported == 0 {
		return
	}
	fmt.Fprintf(b, "- Corpus inventory: **%d imported fixture(s)**, **%d measured**, **%d imported-but-unmeasured**\n",
		imported, measured, unmeasured)
}

func badge(o Outcome) string {
	switch o {
	case OK:
		return "ok"
	case Gap:
		return "**gap**"
	case Fail:
		return "**fail**"
	case Panic:
		return "**PANIC**"
	}
	return string(o)
}

func escapePipe(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
