package probe

import (
	"testing"

	qt "github.com/frankban/quicktest"
)

func TestRenderMarkdownShowsPassingGateWhenNoUnwaivedResults(t *testing.T) {
	c := qt.New(t)
	report := RenderMarkdown([]Result{
		{Outcome: OK, Probe: "probe", Fixture: "fixture", Stage: "stage", Detail: "ok"},
	}, &Waivers{byKey: map[string]string{}}, "atlas-sha", "ptah-version")

	c.Assert(report, qt.Contains, "- Full gate: **0 non-OK** (passes CI)")
}

func TestRenderMarkdownWithCommandShowsSpecificGenerator(t *testing.T) {
	c := qt.New(t)
	report := RenderMarkdownWithCommand([]Result{
		{Outcome: OK, Probe: "probe", Fixture: "fixture", Stage: "stage", Detail: "ok"},
	}, &Waivers{byKey: map[string]string{}}, "atlas-sha", "ptah-version", "make probe-live")

	c.Assert(report, qt.Contains, "This file is generated by `make probe-live`.")
}

func TestRenderLiveMarkdownShowsLiveFixtureSource(t *testing.T) {
	c := qt.New(t)
	report := RenderLiveMarkdownWithCommand([]Result{
		{Outcome: OK, Probe: "roundtrip-consistency", Fixture: "sqlite/fixture", Stage: "roundtrip", Detail: "ok"},
	}, "ptah-version", "make probe-live")

	c.Assert(report, qt.Contains, "# Ptah live database conformance report")
	c.Assert(report, qt.Contains, "first-party Ptah schema fixtures")
	c.Assert(report, qt.Not(qt.Contains), "Atlas fixtures pinned")
}

func TestRenderDifferentialMarkdownShowsLiveDifferentialSource(t *testing.T) {
	c := qt.New(t)
	report := RenderDifferentialMarkdownWithCommand([]Result{
		{Outcome: OK, Probe: "atlas-differential", Fixture: "sqlite/fixture", Stage: "compare", Detail: "ok"},
	}, "atlas-sha", "ptah-version", "make probe-diff")

	c.Assert(report, qt.Contains, "# Ptah vs Atlas CE live differential report")
	c.Assert(report, qt.Contains, "first-party Ptah schema fixtures")
	c.Assert(report, qt.Contains, "Atlas CE binary built from release tag `atlas-sha` pinned in `atlas.version`")
	c.Assert(report, qt.Contains, "## Compared Schema Fact Categories")
	c.Assert(report, qt.Contains, "Schema-qualified table identity and table metadata.")
	c.Assert(report, qt.Contains, "Indexes: ordered columns and expressions")
	c.Assert(report, qt.Not(qt.Contains), "Atlas fixtures pinned")
}

func TestRenderMarkdownShowsFailingGateWhenUnwaivedResultsRemain(t *testing.T) {
	c := qt.New(t)
	report := RenderMarkdown([]Result{
		{Outcome: Gap, Probe: "probe", Fixture: "fixture", Stage: "stage", Detail: "gap"},
	}, &Waivers{byKey: map[string]string{}}, "atlas-sha", "ptah-version")

	c.Assert(report, qt.Contains, "- Full gate: **1 non-OK** (fails CI)")
}

func TestRenderMarkdownKeepsFullGateRedForWaivedResults(t *testing.T) {
	c := qt.New(t)
	report := RenderMarkdown([]Result{
		{Outcome: Gap, Probe: "probe", Fixture: "fixture", Stage: "stage", Detail: "gap"},
	}, &Waivers{byKey: map[string]string{
		waiverKey("probe", "fixture", "stage"): "tracked",
	}}, "atlas-sha", "ptah-version")

	c.Assert(report, qt.Contains, "- Full gate: **1 non-OK** (fails CI)")
	c.Assert(report, qt.Contains, "- Regression budget input: **0 unwaived non-OK**, 1 waived")
}
