package probe

import (
	"strings"
	"testing"

	qt "github.com/frankban/quicktest"
)

func TestRenderMarkdownShowsPassingGateWhenNoUnwaivedResults(t *testing.T) {
	report := RenderMarkdown([]Result{
		{Outcome: OK, Probe: "probe", Fixture: "fixture", Stage: "stage", Detail: "ok"},
	}, &Waivers{byKey: map[string]string{}}, "atlas-sha", "ptah-version")

	if !strings.Contains(report, "- Full gate: **0 non-OK** (passes CI)") {
		t.Fatalf("report does not show passing gate:\n%s", report)
	}
}

func TestRenderMarkdownWithCommandShowsSpecificGenerator(t *testing.T) {
	report := RenderMarkdownWithCommand([]Result{
		{Outcome: OK, Probe: "probe", Fixture: "fixture", Stage: "stage", Detail: "ok"},
	}, &Waivers{byKey: map[string]string{}}, "atlas-sha", "ptah-version", "make probe-live")

	if !strings.Contains(report, "This file is generated by `make probe-live`.") {
		t.Fatalf("report does not show the specific generator command:\n%s", report)
	}
}

func TestRenderLiveMarkdownShowsLiveFixtureSource(t *testing.T) {
	c := qt.New(t)
	report := RenderLiveMarkdownWithCommand([]Result{
		{Outcome: OK, Probe: "roundtrip-consistency", Fixture: "sqlite/fixture", Stage: "roundtrip", Detail: "ok"},
	}, "ptah-version", "make probe-live")

	c.Assert(report, qt.Contains, "# Ptah live database conformance report")
	c.Assert(report, qt.Contains, "first-party Ptah schema fixtures")
	c.Assert(report, qt.Not(qt.Contains), "Atlas fixtures pinned")
}

func TestRenderMarkdownShowsFailingGateWhenUnwaivedResultsRemain(t *testing.T) {
	report := RenderMarkdown([]Result{
		{Outcome: Gap, Probe: "probe", Fixture: "fixture", Stage: "stage", Detail: "gap"},
	}, &Waivers{byKey: map[string]string{}}, "atlas-sha", "ptah-version")

	if !strings.Contains(report, "- Full gate: **1 non-OK** (fails CI)") {
		t.Fatalf("report does not show failing gate:\n%s", report)
	}
}

func TestRenderMarkdownKeepsFullGateRedForWaivedResults(t *testing.T) {
	report := RenderMarkdown([]Result{
		{Outcome: Gap, Probe: "probe", Fixture: "fixture", Stage: "stage", Detail: "gap"},
	}, &Waivers{byKey: map[string]string{
		waiverKey("probe", "fixture", "stage"): "tracked",
	}}, "atlas-sha", "ptah-version")

	if !strings.Contains(report, "- Full gate: **1 non-OK** (fails CI)") {
		t.Fatalf("report does not keep full gate red for waived finding:\n%s", report)
	}
	if !strings.Contains(report, "- Regression budget input: **0 unwaived non-OK**, 1 waived") {
		t.Fatalf("report does not keep waiver scoped to regression budget:\n%s", report)
	}
}
